name: On Push

on:
  push:
    branches:
    - main

jobs:

  backport:
    name: Backport pull request
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
    permissions:
      contents: write
      pull-requests: write
